name: 'Build firmware'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies and arduino compiler cli
        run: |
          apt-get update && apt-get install -y curl git build-essential ffmpeg arduino-mk && apt-get clean
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh


      # - name: Run tests
      #   run: docker run -it omb-2024-nano
